/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  contributionSidebar: [
    {
      // type: "category",
      // label: "Contribution",
      // items: [
      //   "contribution/Open an Issue",
      // ],
      type: "category",
      label: "Contribution",
      link: {
        type: "generated-index",
        title: "Contribution Guides",
        description:
          "Learn how to be a part of us! Contribute to polyphy using these guides.",
        slug: "/contribution",
        keywords: ["contribution"],
      },
      items: [
        "contribution/open-an-issue",
        "contribution/make-a-pull-request",
        "contribution/pull-request-template",
      ],
    },
  ],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      label: "Intro",
      id: "intro",
    },
    {
      type: "category",
      label: "Tutorial",
      items: [
        "tutorial-basics/congratulations",
        "tutorial-basics/create-a-blog-post",
        "tutorial-extras/manage-docs-versions",
      ],
    },
  ],
};

module.exports = sidebars;
